"""add_chat_id_to_telegram_users

Revision ID: 41cefac559f6
Revises: f1e915cfbf2e
Create Date: 2026-01-11 19:38:42.975226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cefac559f6'
down_revision: Union[str, Sequence[str], None] = 'f1e915cfbf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'chat_id')
    # ### end Alembic commands ###
