"""add_role_and_language_to_telegram_users

Revision ID: 8aac70bb2863
Revises: 98dc4eb9fd6c
Create Date: 2026-01-12 16:27:34.246045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aac70bb2863'
down_revision: Union[str, Sequence[str], None] = '98dc4eb9fd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('telegram_users', sa.Column('language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'language')
    op.drop_column('telegram_users', 'role')
    # ### end Alembic commands ###
