"""Add ride indexes

Revision ID: 98dc4eb9fd6c
Revises: bfdb177cd397
Create Date: 2026-01-12 12:02:54.647741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98dc4eb9fd6c'
down_revision: Union[str, Sequence[str], None] = 'bfdb177cd397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ride_offers_search', 'ride_offers', ['start_location', 'end_location', 'travel_start_date'], unique=False)
    op.create_index('ix_ride_requests_search', 'ride_requests', ['start_location', 'end_location', 'travel_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ride_requests_search', table_name='ride_requests')
    op.drop_index('ix_ride_offers_search', table_name='ride_offers')
    # ### end Alembic commands ###
