"""add_is_active_column

Revision ID: be9dde59f8f0
Revises: 8aac70bb2863
Create Date: 2026-01-15 18:58:28.052996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9dde59f8f0'
down_revision: Union[str, Sequence[str], None] = '8aac70bb2863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_offers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_ride_offers_is_active'), 'ride_offers', ['is_active'], unique=False)
    op.add_column('ride_requests', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_ride_requests_is_active'), 'ride_requests', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_requests_is_active'), table_name='ride_requests')
    op.drop_column('ride_requests', 'is_active')
    op.drop_index(op.f('ix_ride_offers_is_active'), table_name='ride_offers')
    op.drop_column('ride_offers', 'is_active')
    # ### end Alembic commands ###
