"""Add price to ride_offers

Revision ID: bfdb177cd397
Revises: 41cefac559f6
Create Date: 2026-01-12 00:25:43.976879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdb177cd397'
down_revision: Union[str, Sequence[str], None] = '41cefac559f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_offers', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_offers', 'price')
    # ### end Alembic commands ###
