"""init rides

Revision ID: f1e915cfbf2e
Revises: bc0384368c26
Create Date: 2025-12-13 18:41:49.744014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e915cfbf2e'
down_revision: Union[str, Sequence[str], None] = 'bc0384368c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_photos',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_photos_id'), 'car_photos', ['id'], unique=False)
    op.create_table('ride_offers',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('request_source', sa.Enum('telegram_app', 'mobile_app', name='request_source_enum'), nullable=False),
    sa.Column('travel_start_date', sa.Date(), nullable=False),
    sa.Column('travel_start_time', sa.Time(), nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('end_location', sa.String(length=255), nullable=False),
    sa.Column('car_model', sa.String(length=100), nullable=False),
    sa.Column('total_seat_amount', sa.Integer(), nullable=False),
    sa.Column('free_seats', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_offers_driver_id'), 'ride_offers', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ride_offers_id'), 'ride_offers', ['id'], unique=False)
    op.create_table('ride_requests',
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('request_source', sa.Enum('telegram_app', 'mobile_app', name='request_source_enum'), nullable=False),
    sa.Column('travel_start_date', sa.Date(), nullable=False),
    sa.Column('travel_start_time', sa.Time(), nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('end_location', sa.String(length=255), nullable=False),
    sa.Column('seat_amount', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_requests_id'), 'ride_requests', ['id'], unique=False)
    op.create_index(op.f('ix_ride_requests_passenger_id'), 'ride_requests', ['passenger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_requests_passenger_id'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_id'), table_name='ride_requests')
    op.drop_table('ride_requests')
    op.drop_index(op.f('ix_ride_offers_id'), table_name='ride_offers')
    op.drop_index(op.f('ix_ride_offers_driver_id'), table_name='ride_offers')
    op.drop_table('ride_offers')
    op.drop_index(op.f('ix_car_photos_id'), table_name='car_photos')
    op.drop_table('car_photos')
    # ### end Alembic commands ###
